import json
import sys

# Load the JSON file generated by Yosys
with open('../design.json') as f:
    design = json.load(f)

# Find the top module by checking the module names in the JSON file
modules = design['modules']
top_module_name = list(modules.keys())[0]  # Assuming the first module is the top module

# Extract all output signals from the top module
output_signals = []
for signal_name, signal_info in modules[top_module_name]['ports'].items():
    if signal_info['direction'] == 'output':
        output_signals.append(signal_name)

# Print the output signals for use in the Bash script
print(' '.join(output_signals))

